version: '3.8'

services:
  app:
    image: ogulcanakca/stock-prediction-app-for-AWS-EC2
    container_name: stock-prediction-app-container-compose-for-AWS-EC2
    ports:
      - "8000:8000" #For API
      - "80:80" #For frontend
    volumes:
      - ./model:/app/model
      - ./scaler:/app/scaler
      - ./app/frontend:/usr/share/nginx/html
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - ENV_VAR=value
  