name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements/requirements_app.txt
        pip install pytest

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .

    - name: Run tests
      run: |
        export PYTHONPATH=.
        pytest

    - name: Build Docker image
      run: docker build -t ogulcanakca/stock-prediction-app-for-server .

    - name: Push to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push ogulcanakca/stock-prediction-app-for-server

    - name: Deploy to Server
      run: |
        echo "${{ secrets.SSH_KEY }}" | ssh -o StrictHostKeyChecking=no -p 2222 -i /dev/stdin ${{ secrets.SSH_USER }}@basebuntuserver.chickenkiller.com<< 'EOF'
        if [ ! -d "/home/ogulcanakca/TimeSeriesForecastAPI-withServer" ]; then
          git clone https://github.com/ogulcanakca/TimeSeriesForecastAPI-withServer.git /home/ogulcanakca/TimeSeriesForecastAPI-withServer
        else
          cd /home/ogulcanakca/TimeSeriesForecastAPI-withServer
          git pull origin main
        fi
        cd /home/ogulcanakca/TimeSeriesForecastAPI-withServer
        docker-compose pull
        docker-compose up -d
        EOF
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
