name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements/requirements_app.txt
        pip install pytest

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .

    - name: Run tests
      run: |
        export PYTHONPATH=.
        pytest

    - name: Build Docker image
      run: docker build -t ogulcanakca/stock-prediction-app-for-server .

    - name: Push to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push ogulcanakca/stock-prediction-app-for-server

    - name: Deploy to AWS EC2
      run: |
        echo "${{ secrets.SSH_KEY }}" > /tmp/id_rsa
        chmod 600 /tmp/id_rsa
        ssh -o StrictHostKeyChecking=no -i /tmp/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
        # Create directory if it doesn't exist
        mkdir -p /home/ogulcanakca/TimeSeriesForecastAPI-withServer
        # Change to the target directory
        cd /home/ogulcanakca/TimeSeriesForecastAPI-withServer
        
        if [ ! -d ".git" ]; then
          git clone https://github.com/ogulcanakca/TimeSeriesForecastAPI-withServer.git .
        else
          git pull origin main
        fi
        
        docker-compose pull
        docker-compose up -d
        EOF
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
